# Generated by Django 2.0.5 on 2018-06-24 17:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Isolates', '0001_initial'),
        ('django_celery_results', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('QC', 'QC'), ('ASSEMBLY', 'ASSEMBLY'), ('ALIGNMENT', 'ALIGNMENT'), ('VARIANT_CALLING', 'VARIANT_CALLING'), ('ANNOTATION', 'ANNOTATION'), ('COVERAGE', 'COVERAGE'), ('RESISTANCE_ANALYSIS', 'RESISTANCE_ANALYSIS')], editable=False, max_length=250)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('result_folder', models.FilePathField(editable=False, null=True)),
                ('seconds', models.IntegerField(default=None, editable=False, null=True)),
                ('additional_parameters', django.contrib.postgres.fields.jsonb.JSONField(default={}, editable=False)),
                ('sample', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='Isolates.Sample')),
                ('task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.TaskResult')),
            ],
        ),
    ]
