# Generated by Django 2.0.5 on 2018-06-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bac_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenttask',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='componenttask',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
