# Generated by Django 2.0.5 on 2019-11-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bac_tasks', '0004_auto_20191020_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenttask',
            name='component_type',
            field=models.CharField(choices=[('QC', 'QC'), ('ASSEMBLY', 'ASSEMBLY'), ('ALIGNMENT', 'ALIGNMENT'), ('VARIANT_CALLING', 'VARIANT_CALLING'), ('ANNOTATION', 'ANNOTATION'), ('COVERAGE', 'COVERAGE'), ('RESISTANCE_ANALYSIS', 'RESISTANCE_ANALYSIS'), ('VIRULENCE_ANALYSIS', 'VIRULENCE_ANALYSIS'), ('REFSEQ_MASHER', 'REFSEQ_MASHER')], editable=False, max_length=250),
        ),
    ]
