version: '3.1'

services:

  db:
    image: postgres:9.6.9
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  nginx:
    image: nginx:1.15.1
    ports:
      - "8090:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - /tmp/bac_static:/static
      - /tmp/bac_media:/media
    depends_on:
      - web
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: ./run_web.sh
    volumes:
      - .:/app  # mount current directory inside container
      - /tmp/bac_static:/static
      - /tmp/bac_media:/media
    ports:
      - "8000:8000"
    # set up links so that web knows about db, rabbit and redis
    links:
      - db
      - rabbitmq
    depends_on:
      - db
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
      - DATABASE_USER=bac
      - DATABASE_PASSWORD=E7470
      - DATABASE_NAME=bac
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - SUPERUSER=bac
      - SUPERUSER_PASSWORD=bac
      - SUPERUSER_EMAIL=bac@bac.com
      - DJANGO_SETTINGS_MODULE=BaC.settings.dev
      - ALLOWED_HOST=localhost;127.0.0.1;0.0.0.0;web
      - STATIC_ROOT=/static
      - MEDIA_ROOT=/media
      - BAC_DB_PATH=/media
      - BAC_SEQUENCE_RESULTS=/media/sequences/results
      - BAC_REFERENCE=/media/sequences

  # Celery worker
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "cd /app; celery -A BaC worker -E -l info"
    volumes:
      - .:/app
      - /tmp/bac_static:/static
      - /tmp/bac_media:/media
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
      - DATABASE_USER=bac
      - DATABASE_PASSWORD=E7470
      - DATABASE_NAME=bac
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - SUPERUSER=bac
      - SUPERUSER_PASSWORD=bac
      - SUPERUSER_EMAIL=bac@bac.com
      - DJANGO_SETTINGS_MODULE=BaC.settings.dev
      - ALLOWED_HOST=localhost;127.0.0.1;0.0.0.0;web
      - STATIC_ROOT=/static
      - MEDIA_ROOT=/media
      - BAC_DB_PATH=/media
      - BAC_SEQUENCE_RESULTS=/media/sequences/results
      - BAC_REFERENCE=/media/sequences