version: '3.1'

services:

  db:
    image: postgres:9.6.9
    restart: always
    volumes:
      - ${DATABASE_LOCAL_FOLDER}:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  nginx:
    image: nginx:1.15.1
    ports:
      - "8090:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${STATIC_LOCAL_FOLDER}:/static
      - ${MEDIA_LOCAL_FOLDER}:/media
    depends_on:
      - web
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: ./run_web.sh
    volumes:
      - .:/app  # mount current directory inside container
      - ${STATIC_LOCAL_FOLDER}:/static
      - ${MEDIA_LOCAL_FOLDER}:/media
    ports:
      - "8000:8000"
    # set up links so that web knows about db, rabbit and redis
    links:
      - db
      - rabbitmq
    depends_on:
      - db
    env_file:
      .env

  # Celery worker
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "cd /app; celery -A BaC worker -E -l info"
    volumes:
      - .:/app
      - ${STATIC_LOCAL_FOLDER}:/static
      - ${MEDIA_LOCAL_FOLDER}:/media
      # needed to execute VirulenceFinder from Celery container
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    depends_on:
      - rabbitmq
    env_file:
      .env

  virulencefinder:
    build:
      context: https://bitbucket.org/genomicepidemiology/virulencefinder.git
      dockerfile: Dockerfile
    entrypoint: /test/test.sh virulencefinder 