from django.db import models


class AntibioticTest(models.Model):
    AMX = models.BooleanField(verbose_name='Amoxicillin(AMX)', default=False)
    AMC = models.BooleanField(verbose_name='Amoxicillin with clavulanic acid(AMC)', default=False)
    OX = models.BooleanField(verbose_name='Oxacillin(OX)', default=False)
    TIC = models.BooleanField(verbose_name='Ticarcillin(TIC)', default=False)
    TCC = models.BooleanField(verbose_name='Ticarcillin-clavulanic acid(TCC)', default=False)
    PIP = models.BooleanField(verbose_name='Piperacillin(PIP)', default=False)
    TZP = models.BooleanField(verbose_name='Piperacillin-tazobactam (TZP)', default=False)
    ATM = models.BooleanField(verbose_name='Aztreonam(ATM)', default=False)
    CF = models.BooleanField(verbose_name='Cefalotin(CF)', default=False)
    CXM = models.BooleanField(verbose_name='Cefuroxime(CXM)', default=False)
    FOX = models.BooleanField(verbose_name='Cefoxitin(FOX)', default=False)
    CTX = models.BooleanField(verbose_name='Cefotaxime(CTX)', default=False)
    CAZ = models.BooleanField(verbose_name='Ceftazidime(CAZ)', default=False)
    CRO = models.BooleanField(verbose_name='Ceftriaxone(CRO)', default=False)
    FEP = models.BooleanField(verbose_name='Cefepime(FEP)', default=False)
    K = models.BooleanField(verbose_name='Kanamycin(K)', default=False)
    GM = models.BooleanField(verbose_name='Gentamicin(GM)', default=False)
    TOB = models.BooleanField(verbose_name='Tobramycin(TOB)', default=False)
    NET = models.BooleanField(verbose_name='Netilmicin(NET)', default=False)
    AN = models.BooleanField(verbose_name='Amikacin(AN)', default=False)
    FOS = models.BooleanField(verbose_name='Fosfomycin(FOS)', default=False)
    RA = models.BooleanField(verbose_name='Rifampin(RA)', default=False)
    C = models.BooleanField(verbose_name='Chloramphenicol(C)', default=False)
    NA = models.BooleanField(verbose_name='Nalidixic acid(NA)', default=False)
    NOR = models.BooleanField(verbose_name='Norfloxacin(NOR)', default=False)
    PEF = models.BooleanField(verbose_name='Plefloxacin(PEF)', default=False)
    OFX = models.BooleanField(verbose_name='Ofloxacin(OFX)', default=False)
    CIP = models.BooleanField(verbose_name='Ciprofloxacin(CIP)', default=False)
    LEV = models.BooleanField(verbose_name='Levofloxacin(LEV)', default=False)
    L = models.BooleanField(verbose_name='Lincomycin(L)', default=False)
    E = models.BooleanField(verbose_name='Erythromycin(E)', default=False)
    CC = models.BooleanField(verbose_name='Clindamycin(CC)', default=False)
    SP = models.BooleanField(verbose_name='Spiramycin(SP)', default=False)
    PR = models.BooleanField(verbose_name='Pristinamycin(PR)', default=False)
    VA = models.BooleanField(verbose_name='Vancomycin(VA)', default=False)
    TEC = models.BooleanField(verbose_name='Teicoplanin(TEC)', default=False)
    SXT = models.BooleanField(verbose_name='Sulfamethoxazole with trimethoprim(SXT)', default=False)
    SSS = models.BooleanField(verbose_name='Triple sulfa(SSS)', default=False)
    TMP = models.BooleanField(verbose_name='Trimethoprim(TMP)', default=False)
    TE = models.BooleanField(verbose_name='Tetracycline(TE)', default=False)
    CS = models.BooleanField(verbose_name='Colistin(CS)', default=False)
    FA = models.BooleanField(verbose_name='Fusidic acid(FA)', default=False)
    LNZ = models.BooleanField(verbose_name='Linezolid(LNZ)', default=False)
    MNO = models.BooleanField(verbose_name='Minocycline(MNO)', default=False)
    FT = models.BooleanField(verbose_name='Nitrofurantoin(FT)', default=False)
    TEL = models.BooleanField(verbose_name='Telithromycin(TEL)', default=False)
    IPM = models.BooleanField(verbose_name='Imipenem(IPM)', default=False)


