# Generated by Django 2.0.5 on 2018-06-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Isolates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacteriaontologyterm',
            name='isolate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phenotype', to='Isolates.Isolate'),
        ),
    ]
