# Generated by Django 2.0.5 on 2018-12-02 12:19

import Isolates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isolates', '0003_auto_20180627_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='assembly_file',
            field=models.FileField(blank=True, null=True, upload_to=Isolates.models.sequence_directory_path, validators=[Isolates.models.fa_validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequence_file_pair1',
            field=models.FileField(blank=True, null=True, upload_to=Isolates.models.sequence_directory_path, validators=[Isolates.models.fq_validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequence_file_pair2',
            field=models.FileField(blank=True, null=True, upload_to=Isolates.models.sequence_directory_path, validators=[Isolates.models.fq_validate_file_extension]),
        ),
    ]
