# Generated by Django 2.0.5 on 2018-12-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isolates', '0004_auto_20181202_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genus', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('order', models.CharField(max_length=255)),
                ('klass', models.CharField(max_length=255)),
                ('phylum', models.CharField(max_length=255)),
                ('kingdom', models.CharField(max_length=255)),
            ],
        ),
    ]
