# Generated by Django 2.0.5 on 2019-01-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isolates', '0005_referencespecies'),
    ]

    operations = [
        migrations.AddField(
            model_name='arogenematch',
            name='nudged',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='assembly',
            field=models.CharField(editable=False, max_length=2555, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='rast_folder',
            field=models.CharField(editable=False, max_length=2555, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='rgi_results',
            field=models.CharField(editable=False, max_length=2555, null=True),
        ),
    ]
