# Generated by Django 2.0.5 on 2019-10-20 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Isolates', '0006_auto_20190120_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirulenceFactor',
            fields=[
                ('virulence_factor_id', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('db_name', models.CharField(editable=False, max_length=250)),
                ('name', models.CharField(editable=False, max_length=250)),
                ('accession', models.CharField(editable=False, max_length=250)),
                ('species', models.CharField(editable=False, max_length=250)),
                ('protein_function', models.CharField(editable=False, max_length=250)),
                ('ncbi_id', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('full_desc', models.CharField(blank=True, editable=False, max_length=2500, null=True)),
                ('organism', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('tax_id', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('link_to_ncbi', models.CharField(blank=True, editable=False, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirulenceFactorHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=2555)),
                ('contig', models.CharField(max_length=255)),
                ('perc_identity', models.FloatField(editable=False)),
                ('hsp_length', models.IntegerField(editable=False)),
                ('template_length', models.IntegerField(editable=False)),
                ('position_in_ref', models.CharField(max_length=255)),
                ('positions_in_contig', models.CharField(max_length=255)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virulence_factor_hit', to='Isolates.Result')),
                ('virulence_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virulence_factor_hit', to='Isolates.VirulenceFactor')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='virulence_finder_results',
            field=models.CharField(editable=False, max_length=2555, null=True),
        ),
    ]
