# Generated by Django 2.0.5 on 2019-11-24 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Isolates', '0008_result_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolate',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='Isolates.Species'),
        ),
    ]
