# Generated by Django 2.0.5 on 2020-04-09 09:26

import Isolates.models.species
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isolates', '0009_auto_20191124_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='resistance_finder_results',
            field=models.CharField(editable=False, max_length=2555, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='sequence_file',
            field=models.FileField(blank=True, null=True, upload_to=Isolates.models.species.sample_sequence_directory_path),
        ),
    ]
