# Generated by Django 2.0.5 on 2020-04-17 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Isolates', '0010_auto_20200409_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResistanceFactor',
            fields=[
                ('resfinder_id', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('accession', models.CharField(editable=False, max_length=250)),
                ('antibiotic', models.CharField(editable=False, max_length=250)),
                ('resistance_gene', models.CharField(editable=False, max_length=250)),
                ('predicted_phenotype', models.CharField(blank=True, editable=False, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResistanceFactorHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=2555)),
                ('contig', models.CharField(max_length=255)),
                ('perc_identity', models.FloatField(editable=False)),
                ('hsp_length', models.IntegerField(editable=False)),
                ('template_length', models.IntegerField(editable=False)),
                ('position_in_ref', models.CharField(max_length=255)),
                ('positions_in_contig', models.CharField(max_length=255)),
                ('resistance_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resistance_factor_hit', to='Isolates.ResistanceFactor')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistance_factor_hit', to='Isolates.Result')),
            ],
        ),
    ]
